apiVersion: apps/v1
kind: Deployment
metadata:
  name: configbackend
  namespace: configbackend
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: configbackend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: configbackend
    spec:
      containers:
      - image: "registry.nosi.cv/na_nos_mon/configbackendch:$BUILD_NUMBER"
        imagePullPolicy: IfNotPresent
        name: configbackend
        ports:
        - containerPort: 8113
          name: 8113tcp01
          protocol: TCP
      imagePullSecrets:
      - name: nanosmon
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
